### ISSUE TITLE
Readme example not working

### ISSUE THREAD

**Issue by b4-io** [perry-birch/leptos-cloudflare#1] opened 2023-01-17 14:31 UTC
Readme example not working. Just to check, does it work for you?

```
Debugger listening on ws://127.0.0.1:44007/e8b975bc-610b-4037-b539-3778c5eba78d
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[mf:inf] Worker reloaded! (506.98KiB)
[mf:inf] Listening on 0.0.0.0:33585
[mf:inf] - http://127.0.0.1:33585
[mf:inf] - http://192.168.188.158:33585
[mf:inf] Updated `Request.cf` object cache!
Tue Jan 17 2023 11:29:18 GMT-0300 (Uruguay Standard Time) - [/], located at: (-34.9007, -56.1291), within: Departamento de Montevideo
[mf:err] Unhandled Promise Rejection: Error: To use the new ReadableStream() constructor, enable the streams_enable_constructors feature flag.
    at Object.construct (/home/dezio/.nvm/versions/node/v18.12.1/lib/node_modules/wrangler/node_modules/@miniflare/core/src/plugins/core.ts:97:13)
    at __wbg_newwithsource_d169ed5262a23b74 (/D/dezio/experimentos/leptos-cloudflare/cloudflare/build/worker/shim.mjs:522:15)
    at null.<anonymous> (wasm://wasm/001dd76e:1:235310)
    at null.<anonymous> (wasm://wasm/001dd76e:1:203952)
    at null.<anonymous> (wasm://wasm/001dd76e:1:6965)
    at null.<anonymous> (wasm://wasm/001dd76e:1:214552)
    at null.<anonymous> (wasm://wasm/001dd76e:1:183690)
    at null.<anonymous> (wasm://wasm/001dd76e:1:242920)
    at __wbg_adapter_30 (/D/dezio/experimentos/leptos-cloudflare/cloudflare/build/worker/shim.mjs:275:16)
    at real (/D/dezio/experimentos/leptos-cloudflare/cloudflare/build/worker/shim.mjs:262:14)
```

**Comment by perry-birch** [comment] 2023-01-28 12:28
Works local with wrangler 2.8.1 with node 19.2.0
I'll look into putting up a dev container to see if it works on a bare image

**Comment by perry-birch** [comment] 2023-02-25 02:51
Going to close this since I've not been able to reproduce

**Closed by perry-birch** 2023-02-25 02:51 UTC
